# Generated by Django 5.2.13 on 2026-05-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_frequency'),
        ('core', '0009_recommendation_sent_in_email'),
    ]

    operations = [
    ]
